-- 0068_bri_qlola_export.sql
--
-- Export bulk transfer yang sudah disetujui final ke format BRI Qlola Mass
-- Transfer (sheet "Transaction Records", profil BI-Fast/BIF).
--
-- Tiga hal yang belum dimiliki KESH untuk memenuhi field wajib Qlola:
--   1. Nomor HP penerima  → kolom S "Ben Mobile Number" (wajib untuk BI-Fast)
--   2. Rekening debit BRI → kolom E "Debit Account" (sama untuk satu batch)
--   3. Nama pengirim      → kolom F "Sender Name" (pemilik rekening debit, satu batch)
--
-- Semua nullable: 19.306 transfer dan 1.035 batch lama tetap terbaca. Baris lama
-- yang datanya tidak lengkap ditolak saat export dengan pesan spesifik, BUKAN
-- di-backfill dengan nilai karangan.

ALTER TABLE transfers
  ADD COLUMN IF NOT EXISTS beneficiary_mobile_number TEXT;

ALTER TABLE transfer_batches
  ADD COLUMN IF NOT EXISTS qlola_debit_account TEXT,
  ADD COLUMN IF NOT EXISTS qlola_sender_name   TEXT;

-- Referensi BIC bank tujuan (kolom G "BenBankIdentifier").
--
-- Sumber: sheet "Bank Code" pada workbook BRI `13-08-2026_Mass Transfer.xlsx`
-- (132 baris, disalin apa adanya). `kesh_bank_code` adalah jembatan ke kode
-- internal katalog bank KESH (TransfersService.getBanks()) — dicocokkan satu per
-- satu berdasarkan nama badan hukum.
--
-- 7 bank di katalog KESH TIDAK ada di sheet BRI dan sengaja dibiarkan tanpa BIC
-- (BRI, BTPN konvensional, Neo Commerce, Allo, Superbank, Krom, Saqu). BIC-nya
-- tidak boleh ditebak: transfer ke bank tersebut diekspor dengan kolom G kosong.
CREATE TABLE IF NOT EXISTS ref_banks (
  bic_code       TEXT PRIMARY KEY,
  bank_code      TEXT NOT NULL,
  name           TEXT NOT NULL,
  kesh_bank_code TEXT UNIQUE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ref_banks_kesh_code ON ref_banks(kesh_bank_code);

INSERT INTO ref_banks (bic_code, bank_code, name, kesh_bank_code) VALUES
  ('KSEIIDJ1', '0', 'PT KUSTODIAN SENTRAL EFEK IND.', NULL),
  ('INDOIDJA', '1', 'BANK INDONESIA', NULL),
  ('BMRIIDJA', '8', 'PT. BANK MANDIRI (PERSERO) TBK', 'MANDIRI'),
  ('BNINIDJA', '9', 'PT. BANK NEGARA INDONESIA (PERSERO)', 'BNI'),
  ('BDINIDJA', '11', 'PT. BANK DANAMON INDONESIA Tbk.', 'DANAMON'),
  ('SYBDIDJ1', '11', 'PT. BANK DANAMON INDONESIA UNIT USAHA SYARIAH', NULL),
  ('SYBBIDJ1', '13', 'PT. BANK PERMATA,TBK UNIT USAHA SYARIAH', NULL),
  ('BBBAIDJA', '13', 'PT. BANK PERMATA,TBK', 'PERMATA'),
  ('CENAIDJA', '14', 'PT. BANK CENTRAL ASIA Tbk.', 'BCA'),
  ('IBBKIDJA', '16', 'PT. BANK MAYBANK INDONESIA Tbk.', 'MAYBANK'),
  ('SYBKIDJ1', '16', 'PT. BANK MAYBANK INDONESIA Tbk. UNIT USAHA SYARIAH', NULL),
  ('PINBIDJA', '19', 'PT. PANIN BANK Tbk.', 'PANIN'),
  ('BNIAIDJA', '22', 'PT. BANK CIMB NIAGA TBK', 'CIMB'),
  ('SYNAIDJ1', '22', 'PT. BANK CIMB NIAGA TBK - UNIT USAHA SYARIAH', NULL),
  ('BBIJIDJA', '23', 'PT. BANK UOB INDONESIA', 'UOB'),
  ('NISPIDJA', '28', 'PT. BANK OCBC NISP, Tbk.', 'OCBC'),
  ('SYONIDJ1', '28', 'PT.BANK OCBC NISP TBK - UNIT USAHA SYARIAH', NULL),
  ('CITIIDJX', '31', 'CITIBANK, NA', 'CITIBANK'),
  ('CHASIDJX', '32', 'KC JPMORGAN CHASE BANK, N.A', NULL),
  ('BOFAID2X', '33', 'BANK OF AMERICA NA', NULL),
  ('MCORIDJA', '36', 'PT. BANK CHINA CONSTRUCTION BANK INDONESIA, TBK', 'CCB'),
  ('ARTGIDJA', '37', 'PT. BANK ARTHA GRAHA INTERNASIONAL, TBK', 'ARTHA_GRAHA'),
  ('BKKBIDJA', '40', 'BANGKOK BANK PUBLIC CO.LTD', NULL),
  ('BOTKIDJX', '42', 'MUFG Bank, Ltd.', NULL),
  ('SUNIIDJ1', '45', 'PT. BANK SUMITOMO MITSUI INDONESIA', NULL),
  ('DBSBIDJA', '46', 'PT. BANK DBS INDONESIA', 'DBS'),
  ('BPIAIDJA', '47', 'PT. BANK RESONA PERDANIA', 'RESONA_PERDANIA'),
  ('MHCCIDJA', '48', 'PT. BANK MIZUHO INDONESIA', NULL),
  ('SCBLIDJX', '50', 'STANDARD CHARTERED BANK', 'STANCHART'),
  ('BCIAIDJA', '54', 'PT BANK CAPITAL INDONESIA', 'CAPITAL'),
  ('BNPAIDJA', '57', 'PT. BANK BNP PARIBAS INDONESIA', 'BNP_PARIBAS'),
  ('ANZBIDJX', '61', 'PT. BANK ANZ INDONESIA', 'ANZ'),
  ('DEUTIDJA', '67', 'DEUTSCHE BANK AG.', NULL),
  ('BKCHIDJA', '69', 'BANK OF CHINA (HONG KONG) LIMITED', NULL),
  ('BBAIIDJA', '76', 'PT. BANK BUMI ARTA', 'BUMI_ARTA'),
  ('HSBCIDJA', '87', 'PT. BANK HSBC INDONESIA', 'HSBC'),
  ('RABOIDJA', '89', 'PT BANK INTERIM INDONESIA', NULL),
  ('CICTIDJA', '95', 'PT. BANK JTRUST INDONESIA, TBK', NULL),
  ('MAYAIDJA', '97', 'PT. BANK MAYAPADA Tbk.', 'MAYAPADA'),
  ('PDJBIDJA', '110', 'PT. BANK PEMBANGUNAN DAERAH JABAR DAN BANTEN', 'BJB'),
  ('SYDKIDJ1', '111', 'PT. BANK DKI UNIT USAHA SYARIAH', NULL),
  ('BDKIIDJ1', '111', 'PT. BANK DKI', 'BPD_DKI'),
  ('PDYKIDJ1', '112', 'PT. BANK PEMBANGUNAN DAERAH DIY', 'BPD_DIY'),
  ('SYYKIDJ1', '112', 'PT.BANK PEMBANGUNAN DAERAH DIY UNIT USAHA SYARIAH', NULL),
  ('PDJGIDJ1', '113', 'PT. BANK PEMBANGUNAN DAERAH JAWA TENGAH', 'BPD_JATENG'),
  ('SYJGIDJ1', '113', 'PT. BANK PEMBANGUNAN DAERAH JATENG UNIT USAHA SYARIAH', NULL),
  ('SYJTIDJ1', '114', 'BANK JATIM UNIT USAHA SYARIAH', NULL),
  ('PDJTIDJ1', '114', 'PT. BANK PEMBANGUNAN DAERAH JATIM', 'BPD_JATIM'),
  ('PDJMIDJ1', '115', 'PT.BANK PEMBANGUNAN DAERAH JAMBI', NULL),
  ('SYJMIDJ1', '115', 'PT. BANK PEMBANGUNAN DAERAH JAMBI UUS', NULL),
  ('SYACIDJ1', '116', 'PT. BANK ACEH SYARIAH', 'BPD_ACEH_SYARIAH'),
  ('PDSUIDJ1', '117', 'PT. BANK PEMBANGUNAN DAERAH SUMUT', 'BPD_SUMUT'),
  ('SYSUIDJ1', '117', 'PT. BANK PEMBANGUNAN DAERAH SUMUT UUS', NULL),
  ('PDSBIDJ1', '118', 'PT. BANK PEMBANGUNAN DAERAH SUMATERA BARAT', 'BPD_NAGARI'),
  ('SYSBIDJ1', '118', 'PT. BANK NAGARI - UNIT USAHA SYARIAH', NULL),
  ('PDRIIDJA', '119', 'PT. BANK PEMBANGUNAN DAERAH RIAU KEPRI', 'BPD_RIAU_KEPRI'),
  ('BSSPIDSP', '120', 'PT. BPD SUMSEL DAN BABEL', 'BPD_SUMSEL_BABEL'),
  ('SYSSIDJ1', '120', 'PT. BPD SUMSEL DAN BABEL UNIT USAHA SYARIAH', NULL),
  ('PDLPIDJ1', '121', 'PT.BANK PEMBANGUNAN DAERAH LAMPUNG', 'BPD_LAMPUNG'),
  ('PDKSIDJ1', '122', 'PT. BANK PEMBANGUNAN DAERAH KALSEL', 'BPD_KALSEL'),
  ('SYKSIDJ1', '122', 'PT. BANK PEMBANGUNAN DAERAH KALSEL - UNIT USAHA SYARIAH', NULL),
  ('PDKBIDJ1', '123', 'PT.BANK PEMBANGUNAN DAERAH KALBAR', 'BPD_KALBAR'),
  ('SYKBIDJ1', '123', 'PT.BANK PEMBANGUNAN DAERAH KALBAR UUS', NULL),
  ('SYKTIDJ1', '124', 'PT.BANK PEMBANGUNAN DAERAH KALTIM DAN KALTARA-UNIT USAHA SYARIAH', NULL),
  ('PDKTIDJ1', '124', 'PT. BANK PEMBANGUNAN DAERAH KALTIM DAN KALTARA', 'BPD_KALTIMTARA'),
  ('PDKGIDJ1', '125', 'PT. BPD KALIMANTAN TENGAH', 'BPD_KALTENG'),
  ('PDWSIDJA', '126', 'PT. BANK SULSELBAR', 'BPD_SULSELBAR'),
  ('SYWSIDJ1', '126', 'PT. BANK SULSELBAR UNIT USAHA SYARIAH', NULL),
  ('PDWUIDJ1', '127', 'PT. BANK PEMBANGUNAN DAERAH SULUT', 'BPD_SULUTGO'),
  ('PDNBIDJ1', '128', 'PT. BANK PEMBANGUNAN DAERAH NUSA TENGGARAT BARAT SYARIAH', 'BPD_NTB_SYARIAH'),
  ('ABALIDBS', '129', 'PT. BANK PEMBANGUNAN DAERAH BALI', NULL),
  ('PDNTIDJ1', '130', 'PT.BANK PEMBANGUNAN DAERAH NTT', 'BPD_NTT'),
  ('PDMLIDJ1', '131', 'PT.BANK PEMBANGUNAN DAERAH MALUKU DAN MALUKU UTARA', 'BPD_MALUKU_MALUT'),
  ('PDIJIDJ1', '132', 'PT.BANK PEMBANGUNAN DAERAH PAPUA', 'BPD_PAPUA'),
  ('PDBKIDJ1', '133', 'PT. BPD BENGKULU', 'BPD_BENGKULU'),
  ('PDWGIDJ1', '134', 'PT. BPD SULAWESI TENGAH', NULL),
  ('PDWRIDJ1', '135', 'PT. BPD SULAWESI TENGGARA', NULL),
  ('PDBBIDJ1', '137', 'PT. BANK PEMBANGUNAN DAERAH BANTEN', NULL),
  ('NUPAIDJ6', '145', 'PT. BANK NUSANTARA PARAHYANGAN', NULL),
  ('SWBAIDJ1', '146', 'PT. BANK OF INDIA INDONESIA, TBK', NULL),
  ('MUABIDJA', '147', 'PT. BANK MUAMALAT INDONESIA', 'MUAMALAT'),
  ('MEDHIDS1', '151', 'PT. BANK MESTIKA DHARMA', 'MESTIKA'),
  ('MEEKIDJ1', '152', 'PT. BANK SHINHAN INDONESIA', 'SHINHAN'),
  ('SYTBIDJ1', '153', 'PT. BANK SINARMAS UNIT USAHA SYARIAH', NULL),
  ('SBJKIDJA', '153', 'PT. BANK SINARMAS', 'SINARMAS'),
  ('MASDIDJ1', '157', 'PT. BANK MASPION', NULL),
  ('GNESIDJA', '161', 'PT. BANK GANESHA', 'GANESHA'),
  ('ICBKIDJA', '164', 'PT. BANK ICBC INDONESIA', 'ICBC'),
  ('AWANIDJA', '167', 'PT. BANK QNB INDONESIA,TBK', 'QNB'),
  ('SYBTIDJ1', '200', 'PT. BANK TABUNGAN NEGARA (PERSERO) UNIT USAHA SYARIAH', NULL),
  ('BTANIDJA', '200', 'PT. BANK TABUNGAN NEGARA (PERSERO)', 'BTN'),
  ('BSDRIDJA', '212', 'PT. BANK WOORI SAUDARA INDONESIA 1906,TBK', 'WOORI'),
  ('SUNIIDJA', '213', 'PT Bank SMBC Indonesia Tbk', 'SMBC'),
  ('SWAGIDJ1', '405', 'PT. BANK VICTORIA SYARIAH', NULL),
  ('SYJBIDJ1', '425', 'PT. BANK JABAR BANTEN SYARIAH', NULL),
  ('MEGAIDJA', '426', 'PT. BANK MEGA Tbk.', 'MEGA'),
  ('BBUKIDJA', '441', 'PT. BANK KB BUKOPIN Tbk.', 'BUKOPIN'),
  ('BSMDIDJA', '451', 'PT BANK SYARIAH INDONESIA', 'BSI'),
  ('BUSTIDJ1', '459', 'PT. BANK BISNIS INTERNASIONAL', NULL),
  ('RIPAIDJ1', '466', 'PT. BANK OKE INDONESIA', NULL),
  ('JSABIDJ1', '472', 'PT. BANK JASA JAKARTA', NULL),
  ('HNBNIDJA', '484', 'PT. BANK KEB HANA INDONESIA', 'HANA'),
  ('BUMIIDJA', '485', 'PT. BANK MNC INTERNASIONAL, TBK', NULL),
  ('YUDBIDJ1', '490', 'PT. BANK YUDHA BHAKTI', NULL),
  ('MGABIDJ1', '491', 'PT. BANK MITRANIAGA', NULL),
  ('AGTBIDJA', '494', 'PT. BANK RAYA INDONESIA TBK', 'RAYA'),
  ('IDMOIDJ1', '498', 'PT. BANK SBI INDONESIA', NULL),
  ('BBLUIDJA', '501', 'PT. BANK DIGITAL BCA', 'BLU_BCA'),
  ('LFIBIDJ1', '503', 'PT. BANK NATIONALNOBU', 'NOBU'),
  ('BUTGIDJ1', '506', 'PT. BANK MEGA SYARIAH', 'MEGA_SYARIAH'),
  ('IAPTIDJA', '513', 'PT. BANK INA PERDANA Tbk', NULL),
  ('ARFAIDJ1', '517', 'PT. BANK PANIN DUBAI SYARIAH', 'PANIN_DUBAI_SYARIAH'),
  ('PMASIDJ1', '520', 'PT. PRIMA MASTER BANK', NULL),
  ('SDOBIDJ1', '521', 'PT. BANK SYARIAH BUKOPIN', NULL),
  ('BDIPIDJ1', '523', 'PT. BANK SAHABAT SAMPOERNA', 'SAHABAT_SAMPOERNA'),
  ('LMANIDJ1', '526', 'PT. BANK DINAR INDONESIA', NULL),
  ('LOMAIDJ1', '531', 'PT. BANK AMAR INDONESIA', NULL),
  ('KSEBIDJ1', '535', 'PT. BANK SEABANK INDONESIA', 'SEABANK'),
  ('BSYAIDJA', '536', 'PT. BANK BCA SYARIAH', NULL),
  ('ATOSIDJ1', '542', 'PT. BANK JAGO Tbk', 'JAGO'),
  ('PUBAIDJ1', '547', 'PT. BANK TABUNGAN PENSIUNAN NASIONAL SYARIAH', 'BTPN_SYARIAH'),
  ('BMSEIDJA', '548', 'PT. BANK MULTI ARTA SENTOSA', 'MULTIARTA_SENTOSA'),
  ('MAYOIDJA', '553', 'PT. BANK MAYORA', NULL),
  ('BIDXIDJA', '555', 'BANK INDEX SELINDO', 'INDEX_SELINDO'),
  ('FAMAIDJ1', '562', 'PT. BANK FAMA INTERNATIONAL', NULL),
  ('SIHBIDJ1', '564', 'PT. BANK MANDIRI TASPEN', NULL),
  ('VICTIDJ1', '566', 'PT. BANK VICTORIA INTERNATIONAL', 'VICTORIA'),
  ('HRDAIDJ1', '567', 'PT. BANK HARDA INTERNATIONAL', NULL),
  ('IBKOIDJA', '945', 'PT. BANK AGRIS', 'IBK'),
  ('NETBIDJA', '947', 'PT BANK ALADIN SYARIAH TBK', 'ALADIN'),
  ('CTCBIDJA', '949', 'PT. BANK CTBC INDONESIA', 'CTBC'),
  ('BICNIDJA', '950', 'PT. BANK COMMONWEALTH', NULL)
ON CONFLICT (bic_code) DO NOTHING;
